import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./ui/navbar";
import { auth0 } from "./lib/auth0";
import { ArrowLeftEndOnRectangleIcon } from "@heroicons/react/20/solid";

//

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth0.getSession();

  if (!session) {
    return (
      <html>
        <body>
          <div className="flex flex-col items-center justify-center h-screen">
            <h1 className="text-4xl">Logueate, maricón</h1>
          <a href="/auth/login"><ArrowLeftEndOnRectangleIcon className="w-10"/></a>
          </div>
        </body>
      </html>
    )
  }
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
